import type { Achievement } from '../types/achievement';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'streak_7',
    title: '일주일 챌린저',
    description: '7일 연속 출석',
    category: 'streak',
    tier: 'bronze',
    icon: '🔥',
    requirement: 7,
    reward: 100,
  },
  {
    id: 'streak_30',
    title: '한 달의 전사',
    description: '30일 연속 출석',
    category: 'streak',
    tier: 'silver',
    icon: '🔥',
    requirement: 30,
    reward: 500,
  },
  {
    id: 'streak_100',
    title: '불굴의 의지',
    description: '100일 연속 출석',
    category: 'streak',
    tier: 'gold',
    icon: '🔥',
    requirement: 100,
    reward: 2000,
  },
  {
    id: 'streak_365',
    title: '전설의 시작',
    description: '365일 연속 출석',
    category: 'streak',
    tier: 'platinum',
    icon: '👑',
    requirement: 365,
    reward: 10000,
  },
  {
    id: 'quest_study_10',
    title: '학업의 달인',
    description: '학업 퀘스트 10개 완료',
    category: 'quest',
    tier: 'bronze',
    icon: '📚',
    requirement: 10,
    reward: 50,
  },
  {
    id: 'quest_study_50',
    title: '학문의 거장',
    description: '학업 퀘스트 50개 완료',
    category: 'quest',
    tier: 'silver',
    icon: '📚',
    requirement: 50,
    reward: 300,
  },
  {
    id: 'quest_health_10',
    title: '건강 지킴이',
    description: '건강 퀘스트 10개 완료',
    category: 'quest',
    tier: 'bronze',
    icon: '💪',
    requirement: 10,
    reward: 50,
  },
  {
    id: 'quest_health_50',
    title: '철인',
    description: '건강 퀘스트 50개 완료',
    category: 'quest',
    tier: 'silver',
    icon: '💪',
    requirement: 50,
    reward: 300,
  },
  {
    id: 'quest_social_10',
    title: '사교왕',
    description: '사회 활동 퀘스트 10개 완료',
    category: 'quest',
    tier: 'bronze',
    icon: '🤝',
    requirement: 10,
    reward: 50,
  },
  {
    id: 'quest_total_100',
    title: '퀘스트 마스터',
    description: '총 100개의 퀘스트 완료',
    category: 'quest',
    tier: 'gold',
    icon: '⭐',
    requirement: 100,
    reward: 1000,
  },
  {
    id: 'level_10',
    title: '초보 탈출',
    description: '레벨 10 달성',
    category: 'level',
    tier: 'bronze',
    icon: '🎯',
    requirement: 10,
    reward: 200,
  },
  {
    id: 'level_25',
    title: '중급자',
    description: '레벨 25 달성',
    category: 'level',
    tier: 'silver',
    icon: '🎯',
    requirement: 25,
    reward: 500,
  },
  {
    id: 'level_50',
    title: '고수',
    description: '레벨 50 달성',
    category: 'level',
    tier: 'gold',
    icon: '🎯',
    requirement: 50,
    reward: 1500,
  },
  {
    id: 'level_100',
    title: '전설',
    description: '레벨 100 달성',
    category: 'level',
    tier: 'platinum',
    icon: '💎',
    requirement: 100,
    reward: 5000,
  },
  {
    id: 'perfect_1',
    title: '첫 완벽한 하루',
    description: '하루 모든 퀘스트 완료 1회',
    category: 'perfect',
    tier: 'bronze',
    icon: '✨',
    requirement: 1,
    reward: 100,
  },
  {
    id: 'perfect_7',
    title: '완벽주의자',
    description: '하루 모든 퀘스트 완료 7회',
    category: 'perfect',
    tier: 'silver',
    icon: '✨',
    requirement: 7,
    reward: 500,
  },
  {
    id: 'perfect_30',
    title: '완벽의 화신',
    description: '하루 모든 퀘스트 완료 30회',
    category: 'perfect',
    tier: 'gold',
    icon: '✨',
    requirement: 30,
    reward: 2000,
  },
];

export const TIER_COLORS = {
  bronze: '#CD7F32',
  silver: '#C0C0C0',
  gold: '#FFD700',
  platinum: '#E5E4E2',
};

export const CATEGORY_LABELS = {
  streak: '연속 출석',
  quest: '퀘스트',
  level: '레벨',
  perfect: '완벽한 하루',
};
